language: node_js
sudo: false
node_js:
  - '12'
  - '14'
env:
  - CXX=g++-8 CC=gcc-8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-8
      - gcc-8
      - libzmq3-dev

script:
  - npm run check-package
  - npm run test
  - npm run jshint

deploy:
  - provider: script
    skip_cleanup: true
    script: bash scripts/travis-deploy.sh
    on:
      repo: dashevo/dashcore-node
      tags: true
